
spring:
  datasource:
    url: jdbc:mysql://i7a101.p.ssafy.io:3306/admin
    username: admin
    password: fN0uC7TNNY?kr&gV]
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: d:\\temp\\spring_uploaded_files

#    url: jdbc:h2:tcp://localhost/~/phorest
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        ddl-auto : none
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8399