spring:
  config:
    import: aws.yaml
  datasource:
    url: jdbc:mysql://i7a101.p.ssafy.io:3306/admin
    username: admin
    password: fN0uC7TNNY?kr&gV]
    driver-class-name: com.mysql.cj.jdbc.Driver


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /var/lib/jenkins/workspace/imagefiles

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        ddl-auto : none
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8399

jwt:
  header: Authorization
  secret: aGVlc3VuLWlzLXRoZS1iZXN0LWdvcmdlb3VzLXBlcmZlY3Qtd29uZGVyZnVsLWZhbnRhc3RpYy1jcmVhdGl2ZS1jaGFybWluZy13b21hbi1pbi10aGUtd29ybGQtZm9yLXN1cmU=
  # 변환함
  token-validity-in-seconds: 86400


