spring:
  config:
    import: aws.yaml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /var/lib/jenkins/workspace/imagefiles

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        ddl-auto : none
        format_sql: true

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace

server:
  port: 8399
